/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yurtyonetimsistemi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilkertinkir
 */
public class ogrenciSil extends javax.swing.JFrame {

    /**
     * Creates new form ogrenciSil
     */
    public ogrenciSil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tcNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        header = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("SİL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("SORGULA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Öğrenci Kimlik Numarası:");

        tcNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcNoActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Öğrenci Adı", "Öğrenci Soyadı", "T.C", "Okul Bilgisi", "Bölüm Bilgisi", "Telefon Numaras", "İzin Durumu", "Yurt Ücreti", "Hastalık Durumu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        header.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        header.setForeground(new java.awt.Color(100, 100, 100));
        header.setText("ÖĞRENCİ SİL:");
        header.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(296, 296, 296))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tcNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(null, "Öğrenciyi silmek istediğinize emin misiniz?",
                "Uyarı", JOptionPane.YES_NO_OPTION);

        if (dialogButton == JOptionPane.YES_OPTION) {
            mysqlConnector msql = new mysqlConnector();
            Connection con = msql.connectorSender();
            String del = tcNo.getText();
            String odaNo = "null";
            String doluluk = "null";
            try {
                Statement stmt = con.createStatement();
                String sorgu1 = String.format("SELECT * from ogrenci where tcNo = %s", del);
                ResultSet rs = stmt.executeQuery(sorgu1);
                Object[] dataArr = null;
                while (rs.next()) {

                    dataArr = new Object[]{rs.getString(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8),
                        rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12)};
                    /*
                id:1, ad:2 , soyad:3, okul:4, tc:5, adres:6,
                bölüm:7, hastalik:8, telefon:9, sınıf:10, odano:11
                     */
                    odaNo = rs.getString(11);
                }
                /*
                (ad,soyad,tcno,okul,bolum,sinif, adres, telefon, hastalikDurumu,odano, kayittarihi )
                 */

                GregorianCalendar gc = new GregorianCalendar();
                java.util.Date date = gc.getTime();
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());

                String sorgu3 = String.format("insert into silinenogrenciler(ad, soyad, okul, tcNo, adres, bolum, hastalikDurumu, telefon, sinif, odano, kayitTarihi, silinmeTarihi) values('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s','%s','%s','%s','%s')",
                        dataArr[1], dataArr[2], dataArr[3], dataArr[4], dataArr[5], dataArr[6], dataArr[7], dataArr[8],
                        dataArr[9], dataArr[10], dataArr[11], sqlDate);
                stmt.executeUpdate(sorgu3);

                stmt = con.createStatement();
                rs = stmt.executeQuery(String.format("SELECT * from odalar oda where oda.idodalar = '%s'", odaNo));               
                while (rs.next()) {
                    if (Integer.parseInt(odaNo) > 0) {
                        doluluk = rs.getString(2);
                        doluluk = "" + (Integer.parseInt(doluluk) - 1);
                    }

                }

                try {
                    String sorgu5 = String.format("Update odalar  set doluluk = '%s' where idodalar='%d'", doluluk, Integer.parseInt(odaNo));
                    stmt.executeUpdate(sorgu5);
                    System.out.println("Kayıt Update Edildi!");
                } catch (Exception e) {
                    System.out.println("Silinemedi2");
                }

                String sorgu2 = String.format("delete from ogrenci where tcno = '%s'", del);
                stmt.executeUpdate(sorgu2);
                System.out.println("Kayıt Silindi");
                
                jLabel2.setText("Kayıt başarıyla silindi!");
                
            } catch (Exception e) {
               
                System.out.println("Silinmedi!");
                jLabel2.setText("Kayıt Silinemedi, hata!");
            }

            /*
                        try{
            Statement stmt = con.createStatement();
            String sorgu = String.format("insert into ogrenci(ad,soyad,tcno,okul,bolum,sinif, adres, telefon, hastalikDurumu,odano, kayittarihi ) values('%s','%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s','%s')",
                    name.getText(), surname.getText(), tcNo.getText(), okulBilgisi.getText(),
                    bolumBilgisi.getText(), sinifBilgisi.getText(), adresBilgisi.getText(),
                    telefonNo.getText(), hastalikBilgisi.getText(), odaNo, sqlDate.toString());
            stmt.executeUpdate(sorgu);
            }
             */
        } else {
            remove(dialogButton);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        mysqlConnector msql = new mysqlConnector();
        Connection con = msql.connectorSender();
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(String.format("SELECT * from ogrenci where tcNo = %s", tcNo.getText()));
            Object[] dataArr = null;

            while (rs.next()) {

                dataArr = new Object[]{rs.getString(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8),
                    rs.getString(9), rs.getString(10), rs.getString(11)};
                /*
                id:1, ad:2 , soyad:3, okul:4, tc:5, adres:6,
                bölüm:7, hastalik:8, telefon:9, sınıf:10, odano:11
                 */

            }
            table.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                        {dataArr[1], dataArr[2], dataArr[4], dataArr[3], dataArr[6], dataArr[8], dataArr[7], dataArr[9], dataArr[10], dataArr[5]}
                    },
                    new String[]{
                        "Öğrenci Adı", "Öğrenci Soyadı", "T.C", "Okul Bilgisi", "Bölüm Bilgisi", "Telefon Numarası", "Hastalık Durumu", "Sınıf", "Oda No", "Adres"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    true, true, true, true, true, true, true, true, true, true
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });

        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tcNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrenciSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogrenciSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tcNo;
    // End of variables declaration//GEN-END:variables
}
